syntax = "proto3";

option csharp_namespace = "Profiles.Api.Protos";

package profiles;

service ProfilesService {
    rpc CreatePatientProfile (CreatePatientRequest) returns (CreatePatientResponse);
    rpc LinkExistingPatientProfile (LinkExistingPatientRequest) returns (LinkExistingPatientResponse);
    rpc ForceCreatePatientProfile (ForceCreatePatientRequest) returns (CreatePatientResponse);
    rpc CreatePatientProfileByReceptionist (CreatePatientByReceptionistRequest) returns (CreatePatientResponse);
    rpc CreateDoctorProfile (CreateDoctorRequest) returns (CreateDoctorResponse);
    rpc CreateReceptionistProfile (CreateReceptionistRequest) returns (CreateReceptionistResponse);

    rpc GetPatients (GetPatientsRequest) returns (GetPatientsResponse);
    rpc GetPatientById (GetPatientByIdRequest) returns (PatientResponse);
    rpc GetMyPatientProfile (GetMyPatientProfileRequest) returns (PatientResponse);
    rpc UpdatePatient (UpdatePatientRequest) returns (UpdatePatientResponse);
    rpc UpdateMyPatientProfile (UpdateMyPatientProfileRequest) returns (UpdatePatientResponse);
    rpc DeletePatient (DeletePatientRequest) returns (DeletePatientResponse);

    rpc GetDoctorCards (GetDoctorCardsRequest) returns (GetDoctorCardsResponse);
    rpc GetDoctorCardById (GetDoctorCardByIdRequest) returns (DoctorCardResponse);
    rpc GetDoctors (GetDoctorsRequest) returns (GetDoctorsResponse);
    rpc GetDoctorById (GetDoctorByIdRequest) returns (DoctorResponse);
    rpc GetMyDoctorProfile (GetMyDoctorProfileRequest) returns (DoctorResponse);
    rpc UpdateDoctor (UpdateDoctorRequest) returns (UpdateDoctorResponse);
    rpc UpdateMyDoctorProfile (UpdateMyDoctorProfileRequest) returns (UpdateDoctorResponse);
    rpc ChangeDoctorStatus (ChangeDoctorStatusRequest) returns (ChangeDoctorStatusResponse);

    rpc GetReceptionists (GetReceptionistsRequest) returns (GetReceptionistsResponse);
    rpc GetReceptionistById (GetReceptionistByIdRequest) returns (ReceptionistResponse);
    rpc GetMyReceptionistProfile (GetMyReceptionistProfileRequest) returns (ReceptionistResponse);
    rpc UpdateReceptionist (UpdateReceptionistRequest) returns (UpdateReceptionistResponse);
    rpc UpdateMyReceptionistProfile (UpdateMyReceptionistProfileRequest) returns (UpdateReceptionistResponse);
    rpc DeleteReceptionist (DeleteReceptionistRequest) returns (DeleteReceptionistResponse);
}

message CreatePatientRequest {
    string account_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string phone_number = 5;
    string date_of_birth = 6;
    string photo_url = 7;
}

message MatchedProfile {
    string profile_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string date_of_birth = 5;
}

message CreatePatientResponse {
    string profile_id = 1;
    bool is_matched = 2;
    MatchedProfile matched_profile = 4;
}

message LinkExistingPatientRequest {
    string account_id = 1;
    string patient_id = 2;
}

message LinkExistingPatientResponse {
}

message ForceCreatePatientRequest {
    string account_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string phone_number = 5;
    string date_of_birth = 6;
    string photo_url = 7;
}

message CreatePatientByReceptionistRequest {
    string first_name = 1;
    string last_name = 2;
    string middle_name = 3;
    string date_of_birth = 4;
}

message CreateDoctorRequest {
    string first_name = 1;
    string last_name = 2;
    string middle_name = 3;
    string date_of_birth = 4;
    string email = 5;
    string specialization_id = 6;
    string office_id = 7;
    int32 career_start_year = 8;
    string status = 9;
    string photo_url = 10;
}

message CreateDoctorResponse {
    string doctor_id = 1;
}

message CreateReceptionistRequest {
    string first_name = 1;
    string last_name = 2;
    string middle_name = 3;
    string email = 4;
    string office_id = 5;
    string photo_url = 6;
}

message CreateReceptionistResponse {
    string receptionist_id = 1;
}

message PatientListItem {
    string patient_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string phone_number = 5;
}

message GetPatientsRequest {
    string search = 1;
}

message GetPatientsResponse {
    repeated PatientListItem patients = 1;
}

message GetPatientByIdRequest {
    string patient_id = 1;
}

message GetMyPatientProfileRequest {
}

message PatientResponse {
    string patient_id = 1;
    string photo_url = 2;
    string first_name = 3;
    string last_name = 4;
    string middle_name = 5;
    string phone_number = 6;
    string date_of_birth = 7;
    bool is_linked_to_account = 8;
}

message UpdatePatientRequest {
    string patient_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string phone_number = 5;
    string date_of_birth = 6;
    string photo_url = 7;
}

message UpdateMyPatientProfileRequest {
    string first_name = 1;
    string last_name = 2;
    string middle_name = 3;
    string phone_number = 4;
    string date_of_birth = 5;
    string photo_url = 6;
}

message UpdatePatientResponse {
}

message DeletePatientRequest {
    string patient_id = 1;
}

message DeletePatientResponse {
}

message DoctorCard {
    string doctor_id = 1;
    string photo_url = 2;
    string first_name = 3;
    string last_name = 4;
    string middle_name = 5;
    string specialization_id = 6;
    string office_id = 7;
    int32 experience_years = 8;
}

message GetDoctorCardsRequest {
    string search = 1;
    string specialization_id = 2;
    string office_id = 3;
}

message GetDoctorCardsResponse {
    repeated DoctorCard doctors = 1;
}

message GetDoctorCardByIdRequest {
    string doctor_id = 1;
}

message DoctorCardResponse {
    DoctorCard doctor = 1;
}

message DoctorListItem {
    string doctor_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string date_of_birth = 5;
    string specialization_id = 6;
    string office_id = 7;
    string status = 8;
}

message GetDoctorsRequest {
    string search = 1;
    string specialization_id = 2;
    string office_id = 3;
}

message GetDoctorsResponse {
    repeated DoctorListItem doctors = 1;
}

message GetDoctorByIdRequest {
    string doctor_id = 1;
}

message GetMyDoctorProfileRequest {
}

message DoctorResponse {
    string doctor_id = 1;
    string photo_url = 2;
    string first_name = 3;
    string last_name = 4;
    string middle_name = 5;
    string date_of_birth = 6;
    string specialization_id = 7;
    string office_id = 8;
    int32 career_start_year = 9;
    int32 experience_years = 10;
    string status = 11;
}

message UpdateDoctorRequest {
    string doctor_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string date_of_birth = 5;
    string specialization_id = 6;
    string office_id = 7;
    int32 career_start_year = 8;
    string status = 9;
    string photo_url = 10;
}

message UpdateMyDoctorProfileRequest {
    string first_name = 1;
    string last_name = 2;
    string middle_name = 3;
    string date_of_birth = 4;
    string specialization_id = 5;
    string office_id = 6;
    int32 career_start_year = 7;
    string photo_url = 8;
}

message UpdateDoctorResponse {
}

message ChangeDoctorStatusRequest {
    string doctor_id = 1;
    string status = 2;
}

message ChangeDoctorStatusResponse {
}

message ReceptionistListItem {
    string receptionist_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string office_id = 5;
    string status = 6;
}

message GetReceptionistsRequest {
}

message GetReceptionistsResponse {
    repeated ReceptionistListItem receptionists = 1;
}

message GetReceptionistByIdRequest {
    string receptionist_id = 1;
}

message GetMyReceptionistProfileRequest {
}

message ReceptionistResponse {
    string receptionist_id = 1;
    string photo_url = 2;
    string first_name = 3;
    string last_name = 4;
    string middle_name = 5;
    string office_id = 6;
    string status = 7;
}

message UpdateReceptionistRequest {
    string receptionist_id = 1;
    string first_name = 2;
    string last_name = 3;
    string middle_name = 4;
    string office_id = 5;
    string status = 6;
    string photo_url = 7;
}

message UpdateMyReceptionistProfileRequest {
    string first_name = 1;
    string last_name = 2;
    string middle_name = 3;
    string office_id = 4;
    string photo_url = 5;
}

message UpdateReceptionistResponse {
}

message DeleteReceptionistRequest {
    string receptionist_id = 1;
}

message DeleteReceptionistResponse {
}
