services:
  gateway-api:
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    container_name: gateway-api
    depends_on:
      - authorization-api
      - profiles-api
      - offices-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JwtSettings__SecretKey=${AUTH_JWT_SECRET_KEY}
      - GrpcClients__Authorization=http://authorization-api:8080
      - GrpcClients__Profiles=http://profiles-api:8080
      - GrpcClients__Offices=http://offices-api:8080
    networks:
      - medical-network
