services:
  authorization-api:
    build:
      context: .
      dockerfile: Authorization/Authorization.Api/Dockerfile
    container_name: authorization-api
    depends_on:
      sql-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=MmcAuthDb;User Id=sa;Password=${SQL_SA_PASSWORD};TrustServerCertificate=True;
      - RabbitMqSettings__Host=rabbitmq
      - RabbitMqSettings__Username=guest
      - RabbitMqSettings__Password=guest
      - JwtSettings__PrivateKey=${AUTH_JWT_PRIVATE_KEY}
      - EmailSettings__Password=${AUTH_EMAIL_PASSWORD}
      - BootstrapAdmin__Email=${BOOTSTRAP_ADMIN_EMAIL}
      - BootstrapAdmin__Password=${BOOTSTRAP_ADMIN_PASSWORD}
      - EmailSettings__ClientAppBaseUrl=http://localhost:5174
    networks:
      - medical-network
