syntax = "proto3";

import "google/protobuf/timestamp.proto";

option csharp_namespace = "Authorization.Api.Protos";

package auth;

service AuthService {
    rpc SignUp (SignUpRequest) returns (SignUpResponse);
    rpc SignIn (SignInRequest) returns (SignInResponse);
    rpc ConfirmEmail (ConfirmEmailRequest) returns (ConfirmEmailResponse);
    rpc Refresh (RefreshRequest) returns (RefreshResponse);
    rpc SignOut (SignOutRequest) returns (SignOutResponse);
}

message SignUpRequest {
    string email = 1;
    string password = 2;
}

message SignUpResponse {
    string account_id = 1;
}

message SignInRequest {
    string email = 1;
    string password = 2;
}

message SignInResponse {
    string account_id = 1;
    string access_token = 2;
    google.protobuf.Timestamp access_token_expires_at = 3;
    string refresh_token = 4;
    google.protobuf.Timestamp refresh_token_expires_at = 5;
}

message ConfirmEmailRequest {
    string token = 1;
}

message ConfirmEmailResponse {
    string account_id = 1;
}

message RefreshRequest {
    string refresh_token = 1;
}

message RefreshResponse {
    string account_id = 1;
    string access_token = 2;
    google.protobuf.Timestamp access_token_expires_at = 3;
    string refresh_token = 4;
    google.protobuf.Timestamp refresh_token_expires_at = 5;
}

message SignOutRequest {
    string refresh_token = 1;
}

message SignOutResponse {
}
