syntax = "proto3";

option csharp_namespace = "Authorization.Api.Protos";

package authInternal;

service AuthInternalService {
    rpc CreateWorkerAccount (CreateWorkerRequest) returns (CreateWorkerResponse);
    rpc DeleteWorkerAccount (DeleteWorkerRequest) returns (DeleteWorkerResponse);
    rpc DeletePatientAccount (DeletePatientRequest) returns (DeletePatientResponse);
}

message CreateWorkerRequest {
    string email = 1;
    string role_name = 2;
    string created_by = 3;
}

message CreateWorkerResponse {
    string account_id = 1;
}

message DeleteWorkerRequest {
    string account_id = 1;
}

message DeleteWorkerResponse {
}

message DeletePatientRequest {
    string account_id = 1;
}

message DeletePatientResponse {
}